# Generated by Django 3.0.8 on 2020-06-30 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myfirstapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#2f4f4f', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CommonColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#2f4f4f', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EachRowColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#2f4f4f', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnCheckAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncheck', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YearDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(default=myfirstapp.models.YearDate.date_now)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(default=myfirstapp.models.Date.date_now)),
                ('eachrowcolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.EachRowColor')),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_created', models.DateField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('checkall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.CheckAll')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.Color')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.Date')),
                ('eachrowcolor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.EachRowColor')),
                ('uncheckall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.UnCheckAll')),
                ('year_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.YearDate')),
            ],
        ),
    ]
