# Generated by Django 3.0.8 on 2020-08-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrUnCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_or_uncheck', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='checkoruncheck',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.CheckOrUnCheck'),
            preserve_default=False,
        ),
    ]
