# Generated by Django 3.0.8 on 2020-08-02 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_auto_20200802_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoruncheck',
            name='checkall',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.CheckAll'),
            preserve_default=False,
        ),
    ]
